### ISSUE TITLE
If we received less than a user_head size buff, the write_pos_ will be moved ahead little by little

### ISSUE THREAD

**Issue by uniqss** [yongxin-ms/asyncio#3]
Suppose len == 1, Decode will do nothing except move write_pos_ ahead.
![image](https://user-images.githubusercontent.com/48117715/221838849-b34977a6-0b53-4446-98bc-f81cdc6a59dd.png)
And if the client peer keep sending len == 1 buffer, the write_pos_ will be moved to some dangerous pos.

**Comment by yongxin-ms** [comment]
if the client peer keeps sending len == 1 data, the new data will be appended to the existing one, so the len will be greater than 1, then the decode logic will be triggered

**Comment by uniqss** [comment]
Oh, you are right. I have tried sending one byte every time, it's just ok. because it is asio's responsibility to copy data to user memory. so the first thing to do for user on callback, is to add the write_pos_.
